ERROR 2018-11-16 09:53:08,411 exception 135 Internal Server Error: /sms_code/13711111111/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/Desktop/django_meiduo/meiduo/meiduo_mall/meiduo_mall/apps/users/views.py", line 15, in get
    sms_code='06d'%randint(0,999999)
TypeError: not all arguments converted during string formatting
ERROR 2018-11-16 09:53:08,635 basehttp 124 "GET /sms_code/13711111111/ HTTP/1.1" 500 17448
ERROR 2018-11-16 09:56:25,702 exception 135 Internal Server Error: /sms_code/13711111111/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/Desktop/django_meiduo/meiduo/meiduo_mall/meiduo_mall/apps/users/views.py", line 15, in get
    sms_code='06d'%randint(0,999999)
TypeError: not all arguments converted during string formatting
ERROR 2018-11-16 09:56:25,818 basehttp 124 "GET /sms_code/13711111111/ HTTP/1.1" 500 18116
ERROR 2018-11-16 09:58:12,938 exception 135 Internal Server Error: /sms_code/13711111111/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/Desktop/django_meiduo/meiduo/meiduo_mall/meiduo_mall/apps/users/views.py", line 17, in get
    coon=get_redis_connection(sms_code)
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/django_env/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for '130253' in settings.CACHES
ERROR 2018-11-16 09:58:32,376 basehttp 124 "GET /sms_code/13711111111/ HTTP/1.1" 500 18505
INFO 2018-11-16 10:18:36,034 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 16
INFO 2018-11-16 10:19:10,038 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 30
INFO 2018-11-16 10:19:11,839 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 30
INFO 2018-11-16 10:19:29,777 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 16
INFO 2018-11-16 10:19:39,672 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 30
INFO 2018-11-16 10:24:44,064 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 16
INFO 2018-11-16 10:24:50,246 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 30
INFO 2018-11-16 11:04:58,653 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 16
WARNING 2018-11-16 11:04:59,525 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 400 30
INFO 2018-11-16 11:14:37,328 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 200 16
WARNING 2018-11-16 11:14:38,298 basehttp 124 "GET /sms_code/18535819899/ HTTP/1.1" 400 30
INFO 2018-11-16 11:16:06,502 basehttp 124 "GET /sms_code/18535819890/ HTTP/1.1" 200 16
WARNING 2018-11-16 20:30:37,895 base 152 Not Found: /
WARNING 2018-11-16 20:30:37,897 basehttp 124 "GET / HTTP/1.1" 404 2104
WARNING 2018-11-16 20:30:37,952 base 152 Not Found: /favicon.ico
WARNING 2018-11-16 20:30:37,955 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2155
ERROR 2018-11-16 20:31:23,802 exception 80 Invalid HTTP_HOST header: 'api.meiduo.com:8000'. You may need to add 'api.meiduo.com' to ALLOWED_HOSTS.
WARNING 2018-11-16 20:31:24,058 basehttp 124 "GET / HTTP/1.1" 400 70219
ERROR 2018-11-16 20:31:24,477 exception 80 Invalid HTTP_HOST header: 'api.meiduo.com:8000'. You may need to add 'api.meiduo.com' to ALLOWED_HOSTS.
WARNING 2018-11-16 20:31:24,530 basehttp 124 "GET /favicon.ico HTTP/1.1" 400 70277
WARNING 2018-11-16 20:32:22,808 base 152 Not Found: /
WARNING 2018-11-16 20:32:22,813 basehttp 124 "GET / HTTP/1.1" 404 2109
WARNING 2018-11-16 20:32:22,865 base 152 Not Found: /favicon.ico
WARNING 2018-11-16 20:32:22,865 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2160
ERROR 2018-11-16 20:37:06,690 exception 80 Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2018-11-16 20:37:06,828 basehttp 124 "GET /sms_code/18535819891/ HTTP/1.1" 400 70456
INFO 2018-11-16 20:37:45,351 basehttp 124 "GET /sms_code/18535819891/ HTTP/1.1" 200 16
INFO 2018-11-16 20:39:54,074 basehttp 124 "GET /sms_code/18535819891/ HTTP/1.1" 200 16
INFO 2018-11-16 20:41:17,942 basehttp 124 "GET /sms_code/18535819891/ HTTP/1.1" 200 16
WARNING 2018-11-16 20:58:43,433 base 152 Not Found: /
WARNING 2018-11-16 20:58:43,434 basehttp 124 "GET / HTTP/1.1" 404 2104
ERROR 2018-11-16 21:01:25,560 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
ERROR 2018-11-16 21:01:25,570 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
WARNING 2018-11-16 21:01:25,657 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 400 71219
WARNING 2018-11-16 21:01:25,662 basehttp 124 "GET /sms_codes/18535819898/ HTTP/1.1" 400 71175
ERROR 2018-11-16 21:01:25,672 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
WARNING 2018-11-16 21:01:25,794 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 400 71219
WARNING 2018-11-16 21:02:32,284 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:02:32,286 base 152 Not Found: /sms_codes/18535819898/
WARNING 2018-11-16 21:02:32,287 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2206
WARNING 2018-11-16 21:02:32,301 basehttp 124 "GET /sms_codes/18535819898/ HTTP/1.1" 404 2194
WARNING 2018-11-16 21:02:32,323 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:02:32,325 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2206
WARNING 2018-11-16 21:03:16,164 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:03:16,182 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2206
WARNING 2018-11-16 21:03:16,197 base 152 Not Found: /sms_codes/18535819898/
WARNING 2018-11-16 21:03:16,208 basehttp 124 "GET /sms_codes/18535819898/ HTTP/1.1" 404 2194
WARNING 2018-11-16 21:03:16,236 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:03:16,237 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2206
WARNING 2018-11-16 21:08:40,791 base 152 Not Found: /mobiles/18535818888/count/
WARNING 2018-11-16 21:08:40,811 basehttp 124 "GET /mobiles/18535818888/count/ HTTP/1.1" 404 2207
WARNING 2018-11-16 21:08:40,827 base 152 Not Found: /mobiles/18535818888/count/
WARNING 2018-11-16 21:08:40,918 basehttp 124 "GET /mobiles/18535818888/count/ HTTP/1.1" 404 2207
INFO 2018-11-16 21:08:41,007 basehttp 124 "GET /sms_codes/18535818888/ HTTP/1.1" 200 16
WARNING 2018-11-16 21:11:44,240 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:11:44,249 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2207
WARNING 2018-11-16 21:11:44,287 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:11:44,297 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2207
INFO 2018-11-16 21:11:44,429 basehttp 124 "GET /sms_codes/18535819898/ HTTP/1.1" 200 16
WARNING 2018-11-16 21:12:46,231 base 152 Not Found: /mobiles/18535819898/count/
WARNING 2018-11-16 21:12:46,258 basehttp 124 "GET /mobiles/18535819898/count/ HTTP/1.1" 404 2207
INFO 2018-11-16 21:12:46,342 basehttp 124 "GET /sms_codes/18535819898/ HTTP/1.1" 200 16
